[workspace]
members = [
    "telemetry_bot",
    "telemetry_core",
]

[profile.release]
codegen-units = 1   # slow down compile-time to improve runtime performance
lto = "fat"         # perform cross-crate LTO
