# ===== BUILD =====
FROM alpine:3 AS build

# Install rust
ENV RUSTFLAGS="-C target-feature=+crt-static"
RUN apk update
RUN apk add rust cargo openssl-dev

# Build the application
RUN mkdir -p /src/telemetry-bot
COPY . /src/telemetry-bot
WORKDIR /src/telemetry-bot
RUN cargo build --release -p telemetry-bot

# ===== DEPLOYMENT =====
FROM alpine:3 as deployment

RUN apk update
RUN apk add openssl-dev

COPY --from=build /src/telemetry-bot/target/release/telemetry-bot /bin/
