CREATE DATABASE telemetry;
CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;
CREATE USER telemetry_bot WITH ENCRYPTED PASSWORD '<REPLACE_WITH_PASSWORD>';
ALTER USER telemetry_bot WITH CREATEROLE;
GRANT ALL PRIVILEGES ON DATABASE telemetry to telemetry_bot;
